version: '3.8'

services:
  flask_app:
    build: ./flask_app
    ports:
      - "5000:5000"
    depends_on:
      - scraper
      - mongo
    networks:
      - app_network

  scraper:
    build: ./scraper_engine
    ports:
      - "5001:5001"
    depends_on:
      - mongo
    networks:
      - app_network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app_network
    volumes:
      - mongo_data:/data/db

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data:
